export {
	useReaderTextLayout,
	COLUMN_WIDTH_PX,
	PAGE_PADDING_CLASS,
	LINE_HEIGHT_VALUE,
	LETTER_SPACING_VALUE,
	PARAGRAPH_SPACING_VALUE,
	WORD_SPACING_VALUE,
	type ReaderColumnWidth,
	type ReaderPagePadding,
	type ReaderLineHeight,
	type ReaderLetterSpacing,
	type ReaderParagraphSpacing,
	type ReaderWordSpacing,
} from "./text-width-store";
